### ISSUE TITLE
Transparant projectvlak

### ISSUE THREAD

**Issue by Quino124** [PBoer90/Studiodin#1]
Bij het aanklikken van een filter-categorie wordt het grijze balkje met projectnaam en klant transparant.
[Schermafbeelding 2017-01-03 om 15.28.57.pdf](https://github.com/PBoer90/Studiodin/files/682384/Schermafbeelding.2017-01-03.om.15.28.57.pdf)

**Comment by Quino124** [comment]
Mobiele weergave laat ook nog te wensen over.
![img_0055](https://cloud.githubusercontent.com/assets/24895400/21610665/aafab648-d1c9-11e6-8f60-2fbda19298d4.PNG)
![img_0056](https://cloud.githubusercontent.com/assets/24895400/21610664/aaf607c4-d1c9-11e6-9375-bdfb73b37804.PNG)

**Comment by Quino124** [comment]
De pagina 'Onze visie' moet echt anders. Misschien dat we dit wel moeten integreren met het portfolio. Dat altijd bovenaan staat. Ik ga sowieso Wim/Marieke hier nog een keer een beter stukje tekst voor laten schrijven.

**Comment by Quino124** [comment]
Filter werkt niet op mobiel

**Comment by Quino124** [comment]
Een keer kijken naar een andere visuele oplossing voor het presenteren van de verschillende beelden in de projectpagina. Bij veel projecten moet je ver naar beneden scrollen om alle beelden te kunnen zien.

**Comment by Quino124** [comment]
Afbeeldingen niet aan de hoogte aan laten passen, maar aan de breedte. 
Nu snijdt 'ie de beelden links en rechts af.

**Comment by PBoer90** [comment]
Done.
